### Get All Users (optional, for testing or admin use)
GET http://localhost:5000/api/users

### 
GET http://localhost:5000/api/trip-experiences

### 
GET http://localhost:5000/api/trip-experiences/trip/75




###

POST http://localhost:5000/api/signup
Content-Type: application/json

{
    "username": "OSU",
    "password": "password",
    "email": "osu@example.com",
    "profile_picture": "link_to_image",
    "bio": "Oregon State University"
}

###

POST http://localhost:5000/api/signup
Content-Type: application/json

{
    "username": "Benny",
    "password": "password",
    "email": "benny@example.com",
    "profile_picture": "link_to_image",
    "bio": "OSU Mascot"
}

### Login with correct password

POST http://localhost:5000/api/login
Content-Type: application/json

{
    "username": "OSU",
    "password": "password"
}

### Login with incorrect password (should fail)

POST http://localhost:5000/api/login
Content-Type: application/json

{
    "username": "OSU",
    "password": "wrongpassword"
}

###

POST http://localhost:5000/api/trips
Content-Type: application/json

{
    "title": "Miami",
    "user_id": 19
}

###

GET http://localhost:5000/api/trips
Content-Type: application/json

###

GET http://localhost:5000/api/experiences
Content-Type: application/json

###

POST http://localhost:5000/api/experiences
Content-Type: application/json

{
    "user_id": 3,
    "title": "Grand Canyon Helicopter Tour",
    "description": "This was such an amazing tour! Our pilot was friendly and had a lot of knowledge to share. Would absolutly recommend especially if you are not afraid of heights!!",
    "rating": 5 
}

###

GET http://localhost:5000/api/trips/user/19
Content-Type: application/json


